apiVersion: v1
kind: ConfigMap
metadata:
  name: divoc-config
  namespace: divoc
  selfLink: /api/v1/namespaces/divoc/configmaps/divoc-config
data:
  DB_HOST: 172.31.25.17
  ENABLE_CERTIFY_ACKNOWLEDGEMENT: ''
  KAFKA_BOOTSTRAP_SERVERS: 172.31.27.143:9092,172.31.26.101:9092,172.31.18.124:9092
  KEYCLOAK_URL: 'http://keycloak-service:8080/auth'
  PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhnCjjILI/H3XSG4vlX1UonWWCn1abJKS+yCJHPruJZfTIPC5IF+b6QA2VuOGJhF/+KvPSbSarQ3IuFZA4b/hariahVPfYQJaF9yzVpkVKii67lGq8QpbSs2Y0s9RvNKofhj2GYKT1zSEAA4sWwEC9gMA+B+sJ2pJIc0zFXbcH03aRkeuavxe8dh3QT190SjQioJx4kQyfVtHD5a3ITQIutHOHFLtAXlY9+urvog/0Q5IYf66q2UHxUYisJIyjXYc7yxbYGFnBBRZjm/6R56/MxCnLrhyzQVkFDpRYh8FEJKA3YXYmRKKkFPqpczHNdOsPoqUzoMf+PyIxVr8ihsH4wIDAQAB
  REGISTRY_URL: http://registry:8081
  REDIS_URL: "redis://172.31.27.143:6379"
  DISABLE_REGISTRY_CALL: ""
  DIGILOCKER_HMAC_AUTHKEY: "UPDATE_KEY_GIVEN_IN_DIGILOCKER"
  ENABLE_KEYCLOAK: "false"
  CLICK_HOUSE_URL: tcp://172.31.25.17:9000?debug=true
  CERTIFICATE_NAMESPACE: "https://cowin.gov.in/credentials/vaccination/v1"
  CERTIFICATE_CONTROLLER_ID: "https://cowin.gov.in/"
  CERTIFICATE_PUBKEY_ID: "https://example.com/i/india"
  CERTIFICATE_DID: "did:india"
  CERTIFICATE_ISSUER: "https://cowin.gov.in/"
  CERTIFICATE_BASE_URL: "https://cowin.gov.in/vaccine/"
  CERTIFICATE_FEEDBACK_BASE_URL: "https://cowin.gov.in/?"
  CERTIFICATE_INFO_BASE_URL: "https://cowin.gov.in/?"
  CERTIFICATE_PRIVATE_KEY: '-----BEGIN RSA PRIVATE KEY-----\nMIIEowIBAAKCAQEAnXQalrgztecTpc+INjRQ8s73FSE1kU5QSlwBdICCVJBUKiuQUt7s+Z5epgCvLVAOCbP1mm5lV7bfgV/iYWDio7lzX4MlJwDedWLiufr3Ajq+79CQiqPaIbZTo0i13zijKtX7wgxQ78wT/HkJRLkFpmGeK3za21tEfttytkhmJYlwaDTEc+Kx3RJqVhVh/dfwJGeuV4Xc/e2NH++ht0ENGuTk44KpQ+pwQVqtW7lmbDZQJoOJ7HYmmoKGJ0qt2hrj15uwcD1WEYfY5N7N0ArTzPgctExtZFDmituLGzuAZfv2AZZ9/7Y+igshzfB0reIFdUKw3cdVTzfv5FNrIqN5pwIDAQABAoIBAHPILMUoLt5UTd5f/YnebqgeCRNAmGOBcwk7HtbMqQoGF93qqvZFd30XOAJZ/ncTpz77Vl95ToxxrWk1WQLCe+ZpOK3Dgk5sFSm8zXx1T64UBNPUSnWoh37C1D39+b9rppCZScgnxlyPdSLy3h3q8Hyoy+auqUEkm/ms5W2lT3fJscyN1IAyHrhsOBWjl3Ilq5GxBo5tbYv/Fb1pQiP/p2SIHA1+2ASXNYQP100F5Vn0V6SFtBXTCQnwcvbP083NvlGxs9+xRs3MCUcxCkKepWuzYwOZDmu/2yCz1/EsP6wlsYEHmCZLdIb0tQt0caqzB/RoxfBpNRIlhOtqHvBzUgECgYEAzIRn5Y7lqO3N+V29wXXtVZjYWvBh7xUfOxAwVYv0rKI0y9kHJHhIrU+wOVOKGISxBKmzqBQRPvXtXW8E0/14Zz82g60rRwtNjvW0UoZAY3KPouwruUIjAe2UnKZcQ//MBTrvds8QGpL6nxvPsBqU0y2K+ySAOxBtNtGEjzv8nxUCgYEAxRbMWukIbgVOuQjangkfJEfA1UaRFQqQ8jUmT9aiq2nREnd4mYP8kNKzJa9L7zj6Un6yLH5DbGspZ2gGODeRw3uVFN8XSzRdLvllNEyiG/waiysUtXfG2DPOR6xD8tXXDMm/tl9gTa8cbkvqYy10XT9MpfOAsusEZVmc0/DBBMsCgYAYdAxoKjnThPuHwWma5BrIjUnxNaTADWp6iWj+EYnjylE9vmlYNvmZn1mWwSJV5Ce2QwQ0KJIXURhcf5W4MypeTfSase3mxLc1TLOO2naAbYY3GL3xnLLK3DlUsZ9+kes3BOD097UZOFG3DIA8sjDxPxTLCoY6ibBFSa/r4GRIMQKBgQCranDCgPu79RHLDVBXM0fKnj2xQXbd/hqjDmcL+Xnx7E7S6OYTXyBENX1qwVQh9ESDi34cBJVPrsSME4WVT3+PreS0CnSQDDMfr/m9ywkTnejYMdgJHOvtDuHSpJlUk3g+vxnm3H0+E5d+trhdGiOjFnLrwyWkd5OTMqWcEEFQkQKBgFfXObDz/7KqeSaAxI8RzXWbI3Fa492b4qQUhbKYVpGn98CCVEFJr11vuB/8AXYCa92OtbwgMw6Ah5JOGzRScJKdipoxo7oc2LJ9sSjjw3RB/aWl35ChvnCJhmfSL8Usbj0nWVTrPwRLjMC2bIxkLtnm9qYXPumW1EjEbusjVMpN\n-----END RSA PRIVATE KEY-----\n'
